### ISSUE TITLE
Regarding the integration

### ISSUE THREAD

**Issue by rakeshkalra1983** [sudheerj/generator-jhipster-primeng#1]
Hi Sudheer

I would first of all like to thank you for your effort. I am really waiting for this integration to be completed.

Kindly help me to understand if I can start using this generator or this is not complete?

**Comment by sudheerj** [comment]
Hi,
  
   The integration is in progress and it will be completed soon. I will confirm the planned date on this weekend.

Regards,

**Comment by sudheerj** [comment]
Please try with latest version now.  Some of the components don't work properly until you copy scripts shown in the instructions or till the next release of JHipster. You can reopen the issue for any concerns.
