### ISSUE TITLE
Ridiculous amount of errors and warning after start

### ISSUE THREAD

**Issue by StephaneMangin** [sudheerj/generator-jhipster-primeng#100]
Hi and thanks for your work,

I have a lot of errors and warnings on a fresh monolitic app installation managed by maven 3.6.0 and npm 6.13.4. Served with npm start.

[primengerrors.txt](https://github.com/sudheerj/generator-jhipster-primeng/files/4366940/primengerrors.txt)

At this stage, i prefer leaving an issue and wait for your return and if you have question.

Thanx

**Comment by sudheerj** [comment]
Hello @StephaneMangin,

    Thanks for notifying. This is an issue due to latest JHipster version. I already informed to JHipster core team about these TSLint issues and I will proceed after their suggestions.

Regards

**Comment by sudheerj** [comment]
The new version 9.0.0 fixed all the issues.
