### ISSUE TITLE
Version 3.0.0 generate errors

### ISSUE THREAD

**Issue by AlvinSanusi** [sudheerj/generator-jhipster-primeng#101]
A newly generated jhipster monolithic app, which run normally, after I add primeng using yo jhipster-primeng, the app can not compile properly when I try ./mvnw.

When starting yo jhipster-primeng, I was greeted with Welcome to the JHipster primeng generator! v3.0.0.And then a series of questions and answers. After that, I slowly see information as follows: 1. Unable to find src/main/webapp/app/vendor.ts or missing required jhipster-needle. file rewrite failed. If I checked the folder, vendor.ts is available.

At the end of the generation there is a message: found 4 vulnerabilities(3 low, 1 moderate) run 'npm audit fix' to fix them, or 'npm audit' for details

I perform npm audit and there is a suggestion to instal quill. So I run npm install quill@1.3.7. After that, I got 3 low vulnerabilities only. The moderate is gone.

But when I run ./mvnw. I still end up with error. 

My system are as follows:
JHipster version is 6.8.0 
java version is 11.0.6 
node version is 13.8.0

Any idea or comment on how to resolve this? Thank you.

**Comment by sudheerj** [comment]
Thanks for notifying the issue. The new version 9.0.0 fixed all the issues.
