### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by kallemdias** [sudheerj/generator-jhipster-primeng#15]
Hi Sudheerj 

I tried to update generator-jhipster-primeng with `npm update -g generator-jhipster-primeng`
but i am getting `npm ERR! cb() never called!`

any idea why this is happening? 

Thanks in advance 

BR
Dias

**Comment by sudheerj** [comment]
Hello Dias,
              I tried with above upgrade/update command without an issue. It might an issue from your end. Can you please try again.

Regards,

**Comment by sudheerj** [comment]
Please reopen if the issue still exists.

**Comment by kallemdias** [comment]
I tried `npm install -g generator-jhipster-primeng-charts`
`/usr/local/lib
└── generator-jhipster-primeng-charts@0.0.3` and it worked fine. 

`npm update -g generator-jhipster-primeng ` is still throwing same error as before.  

here is my current npm version 
 
`npm -version`
`3.10.10`

**Comment by sudheerj** [comment]
Strange. It worked for me. PrimeNG Charts module is deprecated, Can you try npm install -g generator-Jhipster-primeng also.

**Comment by kallemdias** [comment]
` npm install -g generator-Jhipster-primeng` is also throwing the same error. is there a way to deinstall the old version of generator-Jhipster-primeng ?

**Comment by sudheerj** [comment]
I tried on windows machine as well without an issue. Normally either I remove manually or use uninstall command. As per the issue mentioned in the thread it is a common cache issue.  Please follow these steps.

npm cache clean
Manually delete cache from %temp%\npm-*
Command prompt "Run As Administrator"

My npm versions are 4.2.0 and  5.0.4. But it should not an issue with lower versions too. I'am reopening the issue to make sure it works for you as well.

**Comment by kallemdias** [comment]
after cleaning cache + deleting the tmp files and unstalling the old version of generator-Jhipster-primeng, I was able to run `npm install -g generator-Jhipster-primeng`
Now i am facing another issue. but I ll try to fix it my self. .. for now you can close this issue 

Thank you Sudheerj

**Comment by sudheerj** [comment]
Thats great to hear. You can report for any issues you face with this module.  It will be helpful to improve further.
