### ISSUE TITLE
Doesn't work with Yarn

### ISSUE THREAD

**Issue by davidishee** [sudheerj/generator-jhipster-primeng#16]
`> yarn global add generator-jhipster-primeng`

yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "generator-jhipster-primeng@1.0.13" has no binaries
warning No license field
Done in 4.16s.

`> yo jhipster-primeng`

Error jhipster-primeng

You don't seem to have a generator with the name “jhipster-primeng” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster-primeng.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.

If I type "yo", this generator isn't listed.

**Comment by davidishee** [comment]
I tried NPM, and it doesn't show up in the list of generators either.

**Comment by sudheerj** [comment]
It is available through NPM only(for now). Just now I tried with npm install -g generator-jhipster-primeng command and it works for me without an issue. Can you remove manually or uninstall existance version.

https://www.npmjs.com/package/generator-jhipster-primeng

**Comment by sudheerj** [comment]
First We have to install yo globally using 'yarn global add yo' and then 'yarn global add generator-jhipster-primeng'
