### ISSUE TITLE
Error while doing yo jhipster-primeng [searching for vendor.scss]

### ISSUE THREAD

**Issue by hassnainali** [sudheerj/generator-jhipster-primeng#2]
Hi there I've generated jHipster code using generator 4.9.0 and client have .css file and while I'm doing yo jHipster-primeng, i'm facing this issue. I'm unable to understand the cause of this issue why its searching for vendor.scss?????  my client have vendor.css file. Please help

...\***npm\node_modules\generator-jhipster-primeng\generators\app\index.js:238**
                **if (err) throw err;**
                         ^

Error: ENOENT: **no such file or directory**, open 'F:\work.spaces\JHipster\jhipster4.9-app\src\main\webapp\content\scss\vendor.scss'
    at Error (native)

I'm using window 10 + chrome

**Comment by vacuela** [comment]
The same issue
**npm\node_modules\generator-jhipster-primeng\generators\app\index.js:296
                if (err) throw err;**

**Error: ENOENT: no such file or directory, open 'C:\tools\jhipster\bibanitoprime\src\main\webapp\content\scss\vendor.scss'
    at Error (native)**

I'm using windows 10, JHipster Generator 4.9.0

thanks

**Comment by sudheerj** [comment]
The JHipster-PrimeNG module is not yet released due to changes in Core Jhipster. The initial release is available after merge request ported. jhipster/generator-jhipster#6494

You can look at my blog post to know some details about this module
http://sudheerjonna.com/blog/2017/10/09/jhipster-meets-primeng-or-primeng-meets-jhipster/

**Comment by sudheerj** [comment]
Please try with latest version now.  Some of the components don't work properly until you copy scripts shown in the instructions or till the next release of JHipster. You can reopen the issue for any concerns.
