### ISSUE TITLE
Unable to create JHipster 

### ISSUE THREAD

**Issue by Ramprits** [sudheerj/generator-jhipster-primeng#20]
![image](https://user-images.githubusercontent.com/21260321/31987816-a9009a98-b98a-11e7-841d-1471edf7a2cf.png)

**Comment by sudheerj** [comment]
First you should install JHipster before going to install and run this module. Have you done the same way?

**Comment by gsuveti** [comment]
Same issue here. I installed generator-jhipster and after that generator-jhipster-primeng. I get the same error.

**Comment by sudheerj** [comment]
Can you mention the steps followed with the screenshots. I'm not able to replicate the issue.
1. Install JHipster and the module
2. Run yo JHipster and then yo jhipster -primeng

**Comment by gsuveti** [comment]
You are right. I skipped the Introduction part and I misunderstood what this generator does.

**Comment by sudheerj** [comment]
Exactly. Please comment out here if you guys still facing an issue. I'm closing the issue for now.
