### ISSUE TITLE
WizardModule dependency issue.

### ISSUE THREAD

**Issue by shanewow** [sudheerj/generator-jhipster-primeng#22]
Jhipster Version: 4.10.2

I have tried installing generator-jhipster-primeng multiple times and still getting this error. I have cleared out my node_modules and reinstalled. I have also tried installing the "yo jhipster-primeng" with one component and I have tried installing all components and still getting same runtime error while loading the homepage of the app.

I am using the Docker image jhipster/jhipster:v4.10.2 and executing the commands from within the container to run all jhipster commands for building and running application.

<img width="1439" alt="screen shot 2017-11-02 at 12 13 19 pm" src="https://user-images.githubusercontent.com/7637257/32337214-bd6f5c6a-bfc7-11e7-9999-489ad129e180.png">

**Comment by thomaschristensen** [comment]
Could be related to[ issue 11](https://github.com/sudheerj/generator-jhipster-primeng/issues/11)
Ie. could be yarn related. Try npm install.

**Comment by sudheerj** [comment]
We will check the issue and get back to you.Thanks.

**Comment by mathup** [comment]
I have the same issue. 
It is a fresh install. After the ng-generator i deleted nodes modules, npm install and npm start but i the same error appears.

**Comment by sudheerj** [comment]
Please try with latest version version. This issue is fixed.
