### ISSUE TITLE
Unknown version of primeng-extensions on Yarn

### ISSUE THREAD

**Issue by GuiF007** [sudheerj/generator-jhipster-primeng#29]
On version 2.0.16 of the jhipster-primeng, package.json contains the primeng-extensions with version 0.0.17, which is not available during `yarn install`, after adding PrimeNG on a latest jHipster version 4.13.1.

I had to select an available version.

**Comment by sudheerj** [comment]
Thanks. Recently there is an issue with staticInjector of primeng-extensions library. Now the library is updated with latest version.
