### ISSUE TITLE
Error viewing data Components

### ISSUE THREAD

**Issue by poolebu** [sudheerj/generator-jhipster-primeng#32]
Hello!
I'm using version `v2.0.22` with `"jhipsterVersion": "4.13.3"`, and none of the dataset tables work. EG:

![captura de pantalla 2018-01-09 a la s 7 28 15 p m](https://user-images.githubusercontent.com/4500001/34736567-b162a6c0-f573-11e7-8dec-d210ede3a077.png)

**Comment by sudheerj** [comment]
Thanks for reporting. I can able to replicate the issue. It is also occurred due to Angular5 upgrade.

**Comment by sudheerj** [comment]
Fixed in 2.0.23 version. These changes required for HttpClient module.
