### ISSUE TITLE
WizardModule Error

### ISSUE THREAD

**Issue by alexsintoni** [sudheerj/generator-jhipster-primeng#33]
I created a JHipster Monolithic app.
I followed the instruction at https://www.npmjs.com/package/generator-jhipster-primeng to add PrimeNg to that app but when I launch it I get the following error in the console of the browser:

Unexpected value 'WizardModule' imported by the module 'MyModule'. Please add a @NgModule annotation.

In order to be able to launch the app properly I had to remove 'WizardModule' everywhere.
It is only my problem or something else?

**Comment by sudheerj** [comment]
Have you tried with latest 2.0.22 version. Also do npm i command before npm / yarn start.

**Comment by sudheerj** [comment]
Closing the issue as it not replicated. Please comment here if you still face the issue.

**Comment by alexsintoni** [comment]
Hi @sudheerj thanks for the answer. How can i check the installed version of generator-jhipster-primeng? Anyway, I will try to update and create a new JHproject and I will let you know ;) again thanks

**Comment by sudheerj** [comment]
Okay. You can find the latest version in npm module page. As of now latest version is 2.0.25

**Comment by alexsintoni** [comment]
I just tried with last version of JHipster and generator-jhipster-primeng, but still same error:
Uncaught Error: Unexpected value 'WizardModule' imported by the module

**Comment by sudheerj** [comment]
I was not able to replicate the issue. Are you doing production build or dev build? I tried with npm start(refers dev build).

**Comment by sudheerj** [comment]
Thanks for the details. Regarding point 4, try with npm install instead mvn clean install. I tried with latest 2.0.37 version without any issues.


![image](https://user-images.githubusercontent.com/3127317/35419864-5f1a3036-0275-11e8-9752-086148456fba.png)

**Comment by sudheerj** [comment]
Recently one member tried as well.
