### ISSUE TITLE
Webpack production build with demo generated

### ISSUE THREAD

**Issue by LiaoYunheLuke** [sudheerj/generator-jhipster-primeng#34]
Production build 'npm run webpack:prod" encountered error after generate primeng demo, below is detailed error message.

I am using generator-jhipster 4.13.3.

The problem seems to be with module import of  "import {WizardModule} from 'primeng-extensions/components/wizard/wizard.js'. If i removed the import, it seems to be work. But this import statement is in a lot of files, and not used.

****************************************************************************************************************
ERROR in src\main\webapp\app\primeng\menu\menu\menudemo.module.ts(28,9): Error d
uring template compile of 'SampleAppMonolithMenuDemoModule'
  Function expressions are not supported in decorators in 'WizardModule'
    'WizardModule' references '?2'
      '?2' contains the error at primeng-extensions\components\wizard\wizard.js.
ts(134,21)
        Consider changing the function expression into an exported function.

**Comment by sudheerj** [comment]
Yes, I can replicate the issue with webpack:prod. Please try with npm start(webpack:dev) until the issue fixed. Thanks for reporting.

**Comment by riverd3** [comment]
Thank you @sudheerj .
'npm start' works for me, however i can not build it with production profile, if it can be fixed it will be great.

**Comment by sudheerj** [comment]
Glad to hear. I will fix the PROD issue soon.

**Comment by abiieez** [comment]
Has the issue been resolved ?

**Comment by apremkumar1989** [comment]
Even I am facing the same problem with `yarn build`. following is the error details:

```
ERROR in src/main/webapp/app/primeng/menu/menu/menudemo.module.ts(28,9): Error during template compile of 'PghMenuDemoModule'
  Function expressions are not supported in decorators in 'WizardModule'
    'WizardModule' references 'ɵ2'
      'ɵ2' contains the error at primeng-extensions/components/wizard/wizard.js.ts(134,21)
        Consider changing the function expression into an exported function.
```

versions I am using are:
    "primeng": "5.2.0",
    "primeng-extensions": "0.0.41",
    "@angular/core": "5.2.0",

Is this issue fixed or being addressed?

**Comment by ruddell** [comment]
Are you open to converting the use of Wizard to [Steps](https://www.primefaces.org/primeng/#/steps) as it looks the same and is actually included in PrimeNG?

**Comment by sudheerj** [comment]
The steps component UI design is different and no ability to navigate through buttons. If still it creates an issue then I will move to Steps component.

**Comment by Romsan01** [comment]
I am experiencing the same thing.
Is there a fix for this issue?

**Comment by bigjungle** [comment]
my solution : [https://github.com/sudheerj/generator-jhipster-primeng/issues/41]

**Comment by jbalaji01** [comment]
@sudheerj , can you suggest a work around?  
npm start may not be an option for me while bundling jhipster project in prod mode

**Comment by sudheerj** [comment]
@jbalaji01 I'am planning to replace wizard component with steps component. But it involves refactoring in each file. I will get back once it completed

**Comment by jiangzhixiao** [comment]
@sudheerj the same problem when run gradlew -Pprod bootWar

ERROR in primeng-extensions\components\wizard\wizard.js.ts(129,35): Error during template compile of '傻2'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.

**Comment by cdoan123** [comment]
**Error: Expected x arguments, but got y.**

This error occurs when not properly calling/referencing a defined function in a template.  Assume this function is defined:
`foo (bar: string) { }`

The following codes will trigger the above error. 
`<button type="button" label="Expected 1 arguments, but got 0" (onClick)="foo()"></button>`
`<button type="button" label="Expected 1 arguments, but got 2" (onClick)="foo($arg1, $arg2)"></button>`

**Comment by sudheerj** [comment]
Mostly there will be a new release 2.2.0 with in a week to fix this issue. The problem is with extensions config issue in prod environment.

**Comment by sudheerj** [comment]
The PROD issue is fixed from primeng-extensions library and updated the version in our 2.2.0 version.
