### ISSUE TITLE
unable to use primeNG 

### ISSUE THREAD

**Issue by amirensit** [sudheerj/generator-jhipster-primeng#35]
`ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss
Module not found: Error: Can't resolve 'primeng-extensions/resources/primeng-extensions.min.css' in 'C:\Users\amir\Desktop\testJhipster\src\main\webapp\content\scss'
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss 4:10-126
 @ ./src/main/webapp/content/scss/vendor.scss
 @ ./src/main/webapp/app/vendor.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main`

**Comment by ruddell** [comment]
Just delete the line causing the error.  primeng-extensions was updated and that css file no longer exists.  Just a warning - you can't build for production if you use that module because of one of its dependencies  https://github.com/sudheerj/generator-jhipster-primeng/issues/34

**Comment by amirensit** [comment]
Thanks. I hope that the problem  for  build production will be  solved son.

**Comment by sudheerj** [comment]
It was happened due to auto generated commit. The issue is fixed and the PROD issue will be fixed as well. Thanks.
