### ISSUE TITLE
Style not added to JHipster app

### ISSUE THREAD

**Issue by guoyecheng** [sudheerj/generator-jhipster-primeng#40]
Unable to find src/main/webapp/content/scss/vendor.scss or missing required jhipster-needle Style not added to JHipster app

**Comment by sudheerj** [comment]
I can't replicate the issue. You just need to add the suggested needle until it is added in JHipster app

![image](https://user-images.githubusercontent.com/3127317/41498009-0b800a88-7195-11e8-9a11-d4c70fa254e5.png)

**Comment by sudheerj** [comment]
Please comment here if you still can replicate the issue.
