### ISSUE TITLE
Font Awesome icons not working

### ISSUE THREAD

**Issue by drez769** [sudheerj/generator-jhipster-primeng#43]
All icons specific to this project (primeicons/font awesome) either don't work or show up as empty boxes. Very easy to reproduce, just create a new JHipster app (latest version) and follow instructions for generator-jhipster-primeng. For JHipster, I chose most default options as well as Sass and internationalization as it seems required by this generator. For primeng I chose to install all component groups. If necessary I can create a repo for this issue.

It seems like there are issues displaying font awesome icons like `<i>... </i>`? Newer JHipster uses fort-awesome `<fa-icon>`, maybe there's a conflict? I'll try to look into it more but I'm surprised I seem to be the only one with this issue, primeng is currently unusable like this

**Comment by sudheerj** [comment]
I'am trying to replicate this issue. Are you getting this webpack issue while running npm/yarn start
![image](https://user-images.githubusercontent.com/3127317/44952602-d1626400-aeb5-11e8-8164-199e6f34e5e5.png)

**Comment by sudheerj** [comment]
I was able to replicate the issue and fixed this issue with latest upgrade in 2.0.59 release.

**Comment by drez769** [comment]
I don't get that issue, app runs for me. Everything seems to work but the styles are just off. Tested with latest versions of everything at the time, ie generator-jhipster@5.2.1

**Comment by sudheerj** [comment]
It fixed with yarn over npm. You can try to use 2.0.61 release
