### ISSUE TITLE
Error upon initialization. Deprecated method.

### ISSUE THREAD

**Issue by kaigouthro** [sudheerj/generator-jhipster-primeng#52]
Kai@Frank MINGW64 /c/app/aina/var.www/html $ yo jhipster-primeng
WARNING! This method is deprecated. Use getAllJhipsterConfig
Error jhipster-primeng

ERROR! Can't read .yo-rc.json

Kai@Frank MINGW64 /c/app/aina/var.www/html $

**Comment by sudheerj** [comment]
What is the JHipster version you are trying. I didn't find this issue with latest version. Let me check my logs one more time

**Comment by kaigouthro** [comment]
brand spanking new, directly from the website.

**Comment by kaigouthro** [comment]
could it be beacuse i'm using windows? i'm still an amateur programmer. i'm a system design expert, but learning programming, which is completely abstractions made up of 100,000 peoples ideas of how the system should work, and hodge-podging it all together is where the true talent i feel lies in java.. making stuff that shouldn't work together somehow magically work, and 20 times faster, at 1/50th the size, while looking cooler. java... special kind of torture but can't argue with results.
