### ISSUE TITLE
"Translation Not Found" for all components in primeng menu

### ISSUE THREAD

**Issue by smulhall1337** [sudheerj/generator-jhipster-primeng#53]
After running the generator on my project (existing and with a new project), I get the same string for all of the options in the primeng menu on the project.

I've tried this with Jhipster 5.4.2

tested with SASS and international support with no change. 

![primeng](https://user-images.githubusercontent.com/14299394/48092908-ed4af480-e1db-11e8-8845-3c6a818a5df8.PNG)

**Comment by smulhall1337** [comment]
looks like it could have been caused by the odler version of jhipster. I updated the version installed and everything seems fine

**Comment by sudheerj** [comment]
Thanks for the update closing the issue now. We are going to do major development in the coming days.
