### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by uouo690** [sudheerj/generator-jhipster-primeng#72]
Hello ,

I used the instruction of how to install the generator , but I faced this issue.

events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig 

I am using "jhipsterVersion": "5.8.0" , and angular 7.

thanks in advance

**Comment by sudheerj** [comment]
I think its because of latest changes from JHipster side. It is fixed with this PR https://github.com/sudheerj/generator-jhipster-primeng/pull/74

**Comment by uouo690** [comment]
Thanks, I will update now
