### ISSUE TITLE
Question about generator-jhipster-primeng-charts

### ISSUE THREAD

**Issue by pascalgrimaud** [sudheerj/generator-jhipster-primeng#8]
Hi @sudheerj,

I saw you used a lot of my code. I hope it helped you ! I supposed you generated all charts as I did.  

I just want to know if you plan to fully maintain your module, as your module is now a lot of more advanced than mine, so I can put mine as deprecated and put a link to refer to your module. 

Is it ok for you ?

**Comment by sudheerj** [comment]
Hi @pascalgrimaud ,
                 I checked generator-jhipster-primeng-charts project as recommended by JHipster team. You are right, I took the help of this module for PrimeNG module during development.Great work on charts module and it helped me a lot. There is a huge demand for this module in PrimeNG community for the motivation of PrimeNG module development. 
              Yes, I'am going to maintain this module in the long run with more features too. Sure, you can refer this module as it is going to maintain all PrimeNG modules.Thanks.

Regards,

**Comment by pascalgrimaud** [comment]
Ok let's do it! I will put my module as deprecated :)
Good job for this module, I will test it when I have time!
