### ISSUE TITLE
Issue while generating Angular 8+ project

### ISSUE THREAD

**Issue by waleedamjadbutt** [sudheerj/generator-jhipster-primeng#91]
Hi,
I tried to generate a project using your generator. But facing the issue as you can see in the image:
![issue-gen](https://user-images.githubusercontent.com/57687653/72613956-ce550000-3952-11ea-88ce-fe77dbd3b89d.png)

**NodeJS:** 12.13.0
**NPM:** 6.13.2
**Jhipster:** 6.6.0
**Angular:** 8.2.14
**Primeng:** 8.0.2
**jhipster-blueprint:** 0.2.0

**Comment by sudheerj** [comment]
@waleedamjadbutt  We need to generate JHipster project first using `jhipster` command followed by jhipster-primeng commands.
